// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MeetingList;
//
//    var meetingList = MeetingList.FromJson(jsonString);

namespace Zoom_Visitor_s_statistic.JSONS
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class MeetingList
    {
        [JsonProperty("page_count")]
        public long PageCount { get; set; }

        [JsonProperty("page_number")]
        public long PageNumber { get; set; }

        [JsonProperty("page_size")]
        public long PageSize { get; set; }

        [JsonProperty("total_records")]
        public long TotalRecords { get; set; }

        [JsonProperty("meetings")]
        public List<Meeting> Meetings { get; set; }
    }

    public partial class Meeting
    {
        [JsonProperty("uuid")]
        public string Uuid { get; set; }

        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("host_id")]
        public string HostId { get; set; }

        [JsonProperty("topic")]
        public string Topic { get; set; }

        [JsonProperty("type")]
        public long Type { get; set; }

        [JsonProperty("start_time")]
        public DateTimeOffset StartTime { get; set; }

        [JsonProperty("duration")]
        public long Duration { get; set; }

        [JsonProperty("timezone")]
        public string Timezone { get; set; }

        [JsonProperty("created_at")]
        public DateTimeOffset CreatedAt { get; set; }

        [JsonProperty("join_url")]
        public Uri JoinUrl { get; set; }

        [JsonProperty("agenda", NullValueHandling = NullValueHandling.Ignore)]
        public string Agenda { get; set; }
    }

    public partial class MeetingList
    {
        public static MeetingList FromJson(string json) => JsonConvert.DeserializeObject<MeetingList>(json, Converter.Settings);
    }
}

