// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using StudentsInfo;
//
//    var studentsInfo = StudentsInfo.FromJson(jsonString);

namespace Zoom_Visitor_s_statistic.JSONS
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class StudentsInfo
    {
        [JsonProperty("students")]
        public List<Student> Students { get; set; }
    }

    public partial class Student
    {
        [JsonProperty("Email")]
        public string Email { get; set; }

        [JsonProperty("First_Name")]
        public string FirstName { get; set; }

        [JsonProperty("Last_Name")]
        public string LastName { get; set; }

        [JsonProperty("Group")]
        public string Group { get; set; }
    }

    public partial class StudentsInfo
    {
        public static StudentsInfo FromJson(string json) => JsonConvert.DeserializeObject<StudentsInfo>(json, Converter.Settings);
    }
}
