// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using VisitorsStat;
//
//    var visitorsStat = VisitorsStat.FromJson(jsonString);

namespace Zoom_Visitor_s_statistic.JSONS
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class VisitorsStat
    {
        [JsonProperty("page_count")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long PageCount { get; set; }

        [JsonProperty("page_size")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long PageSize { get; set; }

        [JsonProperty("total_records")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long TotalRecords { get; set; }

        [JsonProperty("next_page_token")]
        public string NextPageToken { get; set; }

        [JsonProperty("participants")]
        public List<Participant> Participants { get; set; }
    }

    public partial class Participant
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("user_id")]
        public string UserId { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("user_email")]
        public string UserEmail { get; set; }

        [JsonProperty("join_time")]
        public DateTimeOffset JoinTime { get; set; }

        [JsonProperty("leave_time")]
        public DateTimeOffset LeaveTime { get; set; }

        [JsonProperty("duration")]
        public string Duration { get; set; }
    }

    public partial class VisitorsStat
    {
        public static VisitorsStat FromJson(string json) => JsonConvert.DeserializeObject<VisitorsStat>(json, Converter.Settings);
    }

}

